### ISSUE TITLE
Fuses

### ISSUE THREAD

**Issue by renzenicolai** [badgeteam/why2025-hardware#16]
The 2A fuses on both USB and on battery connector may need to be exchanged for a higher rated fuse as 2A is within normal operating conditions. Maybe use 3A fuses instead?

**Comment by ranzbak** [comment]
I forgot what the problem was, the unrush current, or the fact that some devices can use more in general?

When the Fuses blowing results in a broken port, we might want to consider a poly fuse with a hold current of 2A.

https://www.lcsc.com/product-detail/Resettable-Fuses_BHFUSE-BSMD1206-200-6V_C883134.html

According to the datasheet the resistance is between 0.015 and 0.08Ω, which is 0.24V drop at 3A.
